#!/usr/bin/env python3
"""Compress the standalone weather setup/OTA page into flash with Zopfli.

Run with the PlatformIO Python environment (which includes zopfli).
Run npm --prefix web ci before embedding; Terser minifies the city form script.
"""
from pathlib import Path
import re
import subprocess
import zopfli.gzip

ROOT = Path(__file__).resolve().parents[1]
subprocess.run(["npm", "--prefix", str(ROOT / "web"), "run", "build"], check=True)
html = (ROOT / "web/index.html").read_text()
script = (ROOT / "web/city.min.js").read_text().strip()
html = html.replace('<script src="city.min.js"></script>', "<script>" + script + "</script>")
source = re.sub(r">\s+<", "><", html).strip().encode()
payload = zopfli.gzip.compress(source, numiterations=15)
rows = ["  " + ", ".join(f"0x{b:02x}" for b in payload[i:i + 16]) + ","
        for i in range(0, len(payload), 16)]
(ROOT / "src/WebAssets.generated.h").write_text(
    "#pragma once\n#include <Arduino.h>\n"
    "// Generated by scripts/embed_web.py.\n"
    "const uint8_t kWebAppGzip[] PROGMEM = {\n" + "\n".join(rows) +
    "\n};\nconstexpr size_t kWebAppGzipSize = sizeof(kWebAppGzip);\n")
print(f"Weather portal: {len(source)} -> {len(payload)} bytes")
