#!/usr/bin/env python3
"""Compress the standalone weather setup/OTA page into flash with Zopfli.

Run with the PlatformIO Python environment (which includes zopfli).
The page has no JavaScript, npm dependencies or dashboard schema.
"""
from pathlib import Path
import re
import zopfli.gzip

ROOT = Path(__file__).resolve().parents[1]
source = re.sub(r">\s+<", "><", (ROOT / "web/index.html").read_text()).strip().encode()
payload = zopfli.gzip.compress(source, numiterations=15)
rows = ["  " + ", ".join(f"0x{b:02x}" for b in payload[i:i + 16]) + ","
        for i in range(0, len(payload), 16)]
(ROOT / "src/WebAssets.generated.h").write_text(
    "#pragma once\n#include <Arduino.h>\n"
    "// Generated by scripts/embed_web.py.\n"
    "const uint8_t kWebAppGzip[] PROGMEM = {\n" + "\n".join(rows) +
    "\n};\nconstexpr size_t kWebAppGzipSize = sizeof(kWebAppGzip);\n")
print(f"Weather portal: {len(source)} -> {len(payload)} bytes")
